trigger:
  branches:
    include:
    - '*'
  paths:
    include:
    - src/ScreenMedia.Xenia.WebApi

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  dotnetVersion: '7.x'
  srcPath: 'src/ScreenMedia.Xenia.WebApi/'

steps:
- task: UseDotNet@2
  displayName: 'Install and Use .NET $(dotnetVersion)'
  inputs:
    version: 7.x
    performMultiLevelLookup: true

- task: DotNetCoreCLI@2
  displayName: 'dotnet build $(buildConfiguration)'
  inputs:
    command: 'build'
    projects: '$(srcPath)/ScreenMedia.Xenia.WebApi.sln'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: run unit tests and collect code coverage
  inputs:
    command: 'test'
    projects: '$(srcPath)/**/*.*UnitTests.csproj'
    arguments: '--configuration $(buildConfiguration) --collect:"XPlat Code Coverage"'
    publishTestResults: true

# TODO: Decide on strategy for integration tests - Azure SQL, Virtual Machine, In-Memory Db?

- task: PublishCodeCoverageResults@1
  displayName: 'publish code coverage'
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: $(Agent.TempDirectory)/*/coverage.cobertura.xml
    failIfCoverageEmpty: false #true

- task: DotNetCoreCLI@2
  inputs:
    command: publish
    publishWebProjects: False
    projects: '$(srcPath)/*/ScreenMedia.Xenia.WebApi.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)/WebApi'
    zipAfterPublish: True

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(srcPath)/.pipelines/deployments/'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/Templates'

- publish: '$(Build.ArtifactStagingDirectory)/WebApi'
  displayName: Publish Web Api
  artifact: WebApi

- publish: $(Build.ArtifactStagingDirectory)/Templates
  displayName: Publish Azure Resource Tempaltes
  artifact: ResourceTemplates
