trigger:
  branches:
    include:
    - '*'
  paths:
    include:
    - src/ScreenMedia.Xenia.WebApi

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  dotnetVersion: '7.x'
  srcPath: 'src/ScreenMedia.Xenia.WebApi/'

steps:
- task: UseDotNet@2
  displayName: 'Install and Use .NET $(dotnetVersion)'
  inputs:
    version: 7.x
    performMultiLevelLookup: true

- task: DotNetCoreCLI@2
  displayName: 'dotnet build $(buildConfiguration)'
  inputs:
    command: 'build'
    projects: '$(srcPath)/ScreenMedia.Xenia.WebApi.sln'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: dotnet test and collect code coverage
  inputs:
    command: 'test'
    projects: '$(srcPath)/**/*.*Tests.csproj'
    arguments: '--configuration $(buildConfiguration) --collect:"XPlat Code Coverage"'
    publishTestResults: true

- task: PublishCodeCoverageResults@2
  displayName: 'publish code coverage'
  inputs:
    summaryFileLocation: $(Agent.TempDirectory)/*/coverage.cobertura.xml
    failIfCoverageEmpty: true
